### ISSUE TITLE
Clarify conflicts with existing networking in README

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/boots#10]
The README should clarify if this component will "play nice" with existing networks, or whether it needs to be run in a sandboxed / isolated network.

My worry is that running it on my 192.168.0.0/24 may break all the IP allocations. That concern can be alleviated by stating in the README how this software is designed to be used.

For instance [pixiecore](https://github.com/danderson/netboot/tree/master/pixiecore) by the same author as MetalLB says it uses a DHCP proxy. I'm not sure what path [Plundr takes](https://plndr.io/quickstart/).

**Comment by alexellis** [comment]
<img width="417" alt="Screenshot 2020-04-06 at 10 50 12" src="https://user-images.githubusercontent.com/6358735/78545865-677a1100-77f4-11ea-85d1-e3d1078671ec.png">

**Comment by alexellis** [comment]
@nathangoulding who should this be assigned to, to get it resolved? A simple one-liner in the README is enough to disambiguate and reassure testers.

**Comment by nathangoulding** [comment]
@alexellis is this still valid?

**Comment by ydp** [comment]
Hello, as boots only make sure that other machines won't get IP from boots, but how can we make sure our network booting machine does not get IP from existing DHCP server? Do we still need to add `dhcp-ignore` in existing DHCP server to prevent network booting get IP from existing DHCP server?

**Comment by bingzhangdai** [comment]
Yes, the same question with @ydp. Should we modify the existing DHCP server? @alexellis

**Comment by bingzhangdai** [comment]
Hi @ydp I tried the demo in my local network and carefully checked the logs. You do not need to add the ignore in existing DHCP server. Both existing DHCP and Tinkerbell will respond to DHCP request, and the client will ignore the one without PXE info. Hence only Tinkerbell's DHCP will take effect, which is very handy.

**Comment by bingzhangdai** [comment]
Definitely, I would recommend adding the explanation in README.

**Comment by ydp** [comment]
@bingzhangdai  Thanks for your reply! I did similar test before but get opposite answer. In my experiment, if client does not get pxe info, it just hangs. Maybe this is client related? related to the pxe version which is Nic related?  or I should try more experiments?

**Comment by bingzhangdai** [comment]
@ydp I am not an expert in this area, but I can tell you what I saw.

First, you should check the boot container (if you run the example by docker compose) log to see if Tinkerbell did recieved the DHCP request. You should get something similar to this,
```log
{"level":"info","ts":1691115288.4517825,"caller":"dhcp4-go@v0.0.0-20190402165401-39c137f31ad3/handler.go:105","msg":"","service":"github.com/tinkerbell/boots","pkg":"dhcp","pkg":"dhcp","event":"recv","mac":"ac:1f:6b:ee:0c:dc","via":"0.0.0.0","iface":"ens192","xid":"\"6c:ee:0c:dc\"","type":"DHCPDISCOVER","secs":4}
{"level":"info","ts":1691115288.451905,"caller":"boots/dhcp.go:88","msg":"parsed option82/circuitid","service":"github.com/tinkerbell/boots","pkg":"main","mac":"ac:1f:6b:ee:0c:dc","circuitID":""}
{"level":"info","ts":1691115288.4522583,"caller":"dhcp4-go@v0.0.0-20190402165401-39c137f31ad3/handler.go:61","msg":"","service":"github.com/tinkerbell/boots","pkg":"dhcp","pkg":"dhcp","event":"send","mac":"ac:1f:6b:ee:0c:dc","dst":"255.255.255.255","iface":"ens192","xid":"\"6c:ee:0c:dc\"","type":"DHCPOFFER","address":"10.3.1.21","next_server":"10.3.1.94","filename":"undionly.kpxe"}
```

This indicated that the DHCP was recieved and IP address was assigned.

Actually, I did expereince the hanging during `IPXE initialising devices...` in Hyper-v generation 1 VM, but I still got the above log

![image](https://github.com/tinkerbell/boots/assets/9895061/3143a26d-8bef-4c43-98a9-606bab030149)

I do not know whether it is Tinkerbell's problem or just incompatibility between Tinkerbell and Hyper-v's NIC or PXE. I turned my head to physical machines and then succeeded. By looking carefully at the screeshot, what I can tell for sure is the hanging I encountered had nothing to do with DHCP.

Hope this would help. :)

**Comment by ydp** [comment]
Thank you @bingzhangdai  I will try more experiments!

**Comment by ydp** [comment]
I did more experiments (20 times on 2 machines), only one machine stuck in below status in one time (which could be a potential ipxe or networking issue).
![image](https://github.com/tinkerbell/boots/assets/1532805/0cc560fc-c4ad-4003-aa4e-14521e8200cd)
so, looks like the problem does not exist!!
At least, the first phase when Intel boot agent try to get pxe info, it will not hang, unless there is absolutely no pxe info returned by any dhcp servers, which I also did an experiment, it will hang with error like this:
![image](https://github.com/tinkerbell/boots/assets/1532805/45f8b307-4265-48ac-b1e5-bfbfd9c71fdb)

Then, I found that I actually recorded the process when I had the stuck issue several months ago, below is the screenshot:
![image](https://github.com/tinkerbell/boots/assets/1532805/be2cc090-786e-4d92-b9b6-21c83ade72fd)
Indeed, the Intel boot agent works well, it only hangs at ipxe booting phase.

Then I remembered that back then I did not actually use tinkerbell boots, I was using Openstack Ironic to boot machines, the ipxe binary used was 1.21.1+git-20220113, but now, the ipxe version I am using is 1.0.0+ (from the first screenshot), and I checked the code commit used is https://github.com/tinkerbell/ipxedust/pull/76 , which is using ipxe binary from 2023/03/07, which is much newer. 
So, I guess the old ipxe binary has issue to ignore the incorrect dhcp server, in my case it is `10.106.62.254` , the correct dhcp server should be `10.106.55.171` .  
Anyway, as long as no issue happens like the second screenshot, I would think boots and Intel boot agent work well regarding ignoring other dhcp server.

**Comment by ydp** [comment]
compared the ipxe code in https://github.com/ipxe/ipxe/compare/fbbdc3926...54fcb7c29ce2fabe109286e3c4dfeb297e0f3916 
the most suspicious commit that fixed the dhcp issue is this one https://github.com/ipxe/ipxe/commit/8450fa4a7b9a8236a43b74639fc80bada994ce07 

More info is in 
https://github.com/ipxe/ipxe/pull/798 
https://github.com/ipxe/ipxe/pull/879

**Comment by ydp** [comment]
Oh, I think it's because boots is using embedded script.

**Comment by ydp** [comment]
I guess it's not because the commits, but boots is using embedded ipxe script. see https://github.com/ipxe/ipxe/issues/395#issuecomment-864499966

**Comment by bingzhangdai** [comment]
Glad to hear. "No boot framework" or "nothing to boot" may also result from missing files from tftp like initramfs-aarch64, initramfs-x86_64, vmlinuz-aarch64, vmlinuz-x86_64 or so. I can see the error from boots log. Anyway, it is merely a minor problem :)

**Comment by ydp** [comment]
Hi @bingzhangdai  Just let you know, I am still not convinced by the experiment result, and asked questions in https://github.com/ipxe/ipxe/discussions/1012 , they told me it should be undefined behavior. So for safety reason, even though my several experiments showed success, I will still switch back to "only one DHCP" environment.
