### ISSUE TITLE
git-lfs instructions don't work on my OS

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/boots#11]
The git-lfs instructions don't work on my OS:

<img width="522" alt="Screenshot 2020-04-06 at 10 48 53" src="https://user-images.githubusercontent.com/6358735/78545753-3bf72680-77f4-11ea-86f6-41c0cf80a30f.png">

Are there further instructions and/or testing required? Is there an assumed base-OS which isn't being communicated in the README?

Tested the instructions on Ubuntu 18.04 and Arch Linux with the same error:

```
[alex@nuc boots]$ uname -a
Linux nuc 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
[alex@nuc boots]$ git lfs install
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log
[alex@nuc boots]$ git lfs pull
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log
[alex@nuc boots]$ git version
git version 2.26.0
[alex@nuc boots]$ 
```

**Comment by vielmetti** [comment]
For reference I was able to handle this with an `apt-get install git-lfs` before proceeding with the rest of the instructions.

There is a wiki here https://github.com/git-lfs/git-lfs/wiki/Installation with details, including some gory details for build from scratch.

**Comment by alexellis** [comment]
Seems I've created two issues somehow.

See also: #12

**Comment by gauravgahlot** [comment]
Closing this issue, as it has been already addressed in issue #12.

**Comment by alexellis** [comment]
@gauravgahlot whilst the link is better, the instructions are still a little on the ambiguous side.

May I suggest changing to:

```
# Install "git-lfs" package for your OS, i.e.:  apt-get install git-lf
# Then run these two commands:

git lfs install
git pull install
```

**Comment by alexellis** [comment]
@gauravgahlot my bad, this wasn't a duplicate, it was separate to clarify the instructions. The other was to fix the link to be more helpful for Linux users.

**Comment by parauliya** [comment]
@alexellis Actually git-lfs won't be even required for the setup and we will be removing this from document as well once our testing will be completed.
