### ISSUE TITLE
Boots should pass Osie to registered hardware without workflow yet

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/boots#114]
## Expected Behaviour
A registered hardware without a workflow registered should boot into Osie.

## Current Behaviour
Boots logs:

```
{"level":"info","ts":1608652334.4974012,"caller":"boots/dhcp.go:76","msg":"retrieved job is empty","service":"github.com/tinkerbell/boots","pkg":"main","type":"DHCPDISCOVER","mac":"f4:4d:30:64:8e:0f","err":"discover from dhcp message: get hardware by mac from tink: rpc error: code = Unknown desc = unexpected end of JSON input","errVerbose":"rpc error: code = Unknown desc = unexpected end of JSON input\nget hardware by mac from tink\ngithub.com/tinkerbell/boots/packet.(*Client).DiscoverHardwareFromDHCP\n\t/home/runner/work/boots/boots/packet/endpoints.go:104\ngithub.com/tinkerbell/boots/job.discoverHardwareFromDHCP.func1\n\t/home/runner/work/boots/boots/job/fetch.go:16\ngithub.com/golang/groupcache/singleflight.(*Group).Do\n\t/home/runner/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20190702054246-869f871628b6/singleflight/singleflight.go:56\ngithub.com/tinkerbell/boots/job.discoverHardwareFromDHCP\n\t/home/runner/work/boots/boots/job/fetch.go:18\ngithub.com/tinkerbell/boots/job.CreateFromDHCP\n\t/home/runner/work/boots/boots/job/job.go:59\nmain.dhcpHandler.serveDHCP\n\t/home/runner/work/boots/boots/dhcp.go:74\nmain.dhcpHandler.ServeDHCP.func1\n\t/home/runner/work/boots/boots/dhcp.go:45\ngithub.com/gammazero/workerpool.startWorker\n\t/home/runner/go/pkg/mod/github.com/gammazero/workerpool@v0.0.0-20200311205957-7b00833861c6/workerpool.go:218\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/asm_386.s:1333\ndiscover from dhcp message"}
```
And it does not serve Osie via iPXE

## Possible Solution

Serve osie even if there are not workflow registered.

## Steps to Reproduce (for bugs)
1. Start tinkerbell with Vagrant or what ever
2. Register hardware
3. Start the hardware without any workflow

## Context

In my home lab I do not persist operating system in all the devices, I like to have a few of them "ephemeral" and Osie is perfect for that, but I have to push a hell world workflow otherwise they won't even boot

## Your Environment

Sandbox!

**Comment by mmlb** [comment]
Yeah that lines up with https://github.com/tinkerbell/proposals/tree/master/proposals/0016. We'd need a configuration for a default address pool we can hand out IPs from.

**Comment by gianarb** [comment]
I think it is related but not strictly related. I am registering my own hardware at the moment so IP is set, but BOOTS is too self defensive and it does not care because a workflow is not registered. The workaround for me is to have a hello world workflow for each hardware.

**Comment by mmlb** [comment]
oh sorry I didn't fully grasp that. Yep I think that makes a ton of sense.
