### ISSUE TITLE
Remove binaries from the project

### ISSUE THREAD

**Issue by displague** [tinkerbell/boots#116]
## Expected Behaviour

Project binaries should be external artifacts, built through automation, not included in the git repository.

## Current Behaviour

Binaries are included in the project and are expected to be compiled and updated by contributors. The binaries must then be manually verified through recompiling (with the same tools) and checksum verification.  This slows our ability to accept new changes (#79).

## Possible Solution

Similar to #4, the ipxe/bin artifacts should be published to GitHub if they are needed outside of a boots container. If a boots container image is sufficient, the binaries should be compiled at image build time, not trusted from the repository.

The LFS ipxe/bin artifacts should then be removed and the instructions (https://github.com/tinkerbell/boots#local-setup) updated accordingly.

**Comment by geekgonecrazy** [comment]
This would help a lot.  A few other changes I’d like to contribute here on this code base but that part made this component one I drag my feet wanting to even touch

**Comment by mmlb** [comment]
Yep I think this will definitely help getting things upstream, my main hangup is that then this code base then loses its `go get`edness.

**Comment by mmlb** [comment]
:fist_right: lfs, https://github.com/tinkerbell/boots/pull/79#issuecomment-761007091. I guess just one more reason for this then :D.
