### ISSUE TITLE
Worker doesn't pick up the new workflow 

### ISSUE THREAD

**Issue by Cbkhare** [tinkerbell/boots#125]
When a worker is rebooted via an action in the workflow, The worker picks up the workflow which is stuck in `running` state and as a result, it **never** picks up the new workflow.
This is in reference to the recent commit https://github.com/tinkerbell/boots/pull/115. 

## Expected Behaviour
Ideally, changes in this commit https://github.com/tinkerbell/boots/pull/115 should be rectified to handle the following scenario. 
- tink-server should have a mechanism to execute/resume running workflow after reboot.
- When rebooted via workflow either workflow should be marked as completed. 
- Or worker should pick up new workflow (if there is one defined for it).

## Current Behaviour.

Below are the stepwise states happening right now. 
- worker does ipxeboot.
- worker executes the workflow.
- worker reboots as a part of workflow.
- worker, after reboot, retries to pxe boot  (because of https://github.com/tinkerbell/boots/pull/115 ) and fails. 

- When a new workflow is created. 
- Worker stills picks up the workflow which is running state and against, fails.

## Steps to Reproduce (for bugs)
- Create a workflow using the below template. 
- Use any alpine image for executing `reboot` action.
```
version: "0.1"
name: try-install
global_timeout: 1800
tasks:
  - name: "hello world"
    worker: "{{.device_1}}"
    actions:
      - name: "hello_world"
        image: hello-world
        timeout: 60
      - name: "reboot"
        image: alpine-image
        command:
          - bash
          - -c
          - |
            echo 1 > /proc/sys/kernel/sysrq; echo b > /proc/sysrq-trigger
```
Observe steps as mentioned in current behaviour. 

- State of first workflow 
```
docker exec -i deploy_tink-cli_1 tink workflow state 88241ed8-6221-11eb-af88-0242ac120005 
+----------------------+--------------------------------------+
| FIELD NAME           | VALUES                               |
+----------------------+--------------------------------------+
| Workflow ID          | 88241ed8-6221-11eb-af88-0242ac120005 |
| Workflow Progress    | 50%                                  |
| Current Task         | hello world                          |
| Current Action       | reboot                               |
| Current Worker       | 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a95 |
| Current Action State | STATE_RUNNING                        |
+----------------------+--------------------------------------+
```
- state of the worker after reboot action.

![image](https://user-images.githubusercontent.com/13061957/106267946-6537e600-6250-11eb-8fc8-bc03efd02bce.png)

- Create a new workflow. 
- worker still picks up the old workflow because of https://github.com/tinkerbell/boots/pull/115 and fails again. 
![image](https://user-images.githubusercontent.com/13061957/106268286-e2fbf180-6250-11eb-8bca-0a58d4498661.png)
- Both of the workflow new and old, are stuck at their respective state. 
```
vagrant@provisioner:/vagrant/deploy/centos$ docker exec -i deploy_tink-cli_1 tink workflow state 88241ed8-6221-11eb-af88-0242ac120005 
+----------------------+--------------------------------------+
| FIELD NAME           | VALUES                               |
+----------------------+--------------------------------------+
| Workflow ID          | 88241ed8-6221-11eb-af88-0242ac120005 |
| Workflow Progress    | 50%                                  |
| Current Task         | hello world                          |
| Current Action       | reboot                               |
| Current Worker       | 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a95 |
| Current Action State | STATE_RUNNING                        |
+----------------------+--------------------------------------+
vagrant@provisioner:/vagrant/deploy/centos$ docker exec -i deploy_tink-cli_1 tink workflow state 5894621e-6222-11eb-af88-0242ac120005
+----------------------+--------------------------------------+
| FIELD NAME           | VALUES                               |
+----------------------+--------------------------------------+
| Workflow ID          | 5894621e-6222-11eb-af88-0242ac120005 |
| Workflow Progress    | 0%                                   |
| Current Task         |                                      |
| Current Action       |                                      |
| Current Worker       |                                      |
| Current Action State | STATE_PENDING                        |
+----------------------+--------------------------------------+

```

**Result: If used for OS installation and worker is rebooted as a part of the workflow. The worker will never come up.**

## Context
- Creating a centos workflow. 

## Your Environment
- Vagrant

**Comment by mmlb** [comment]
We can't do anything about this at the moment I think. The way around this is to sleep for a little bit before doing the echo so that tink-worker has had the ability to send progress to tink-server.

**Comment by mmlb** [comment]
Hmm can you give boots logs for the attempted dhcp. It should allow the dhcp/tftp/...netboot.

**Comment by mmlb** [comment]
The action is the issue here, as written it doesn't allow for tink-server to report back success and so naturally we re-run it. This is working as intended. You'll want to use the reboot action from https://github.com/tinkerbell/hub/issues/13 when its ready.
