### ISSUE TITLE
Question on HTTP endpoints purpose

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/boots#132]
Hello, I am wondering what the use-cases are for Boots serving these HTTP endpoints?

- [/hardware-components](https://github.com/tinkerbell/boots/blob/70440b27cb1559770ef485596b9c3a4a253a4dfc/http.go#L82)
- [/problem](https://github.com/tinkerbell/boots/blob/70440b27cb1559770ef485596b9c3a4a253a4dfc/http.go#L71)
- [/phone-home](https://github.com/tinkerbell/boots/blob/70440b27cb1559770ef485596b9c3a4a253a4dfc/http.go#L69)

I'm having trouble finding any docs or even code comments on their purpose. Thanks so much!

**Comment by mmlb** [comment]
Good questions and def in need of being documented. These are all things that we want to remove from boots in the near future, one of the reasons for workflow services.

/hardware-components: Is used to post back discovered hw and fw versions. Its used during hw discovery and during deprovision.

/problem: Is used by osie for provision/deprovision to pass a failure from the scripts.

/phone-home: Is used to pass in progress information from OSIE and also the final phone-home/activation signal from cloud-init. The progress info end up showing up in the EM console provision progress/history.

**Comment by jacobweinstock** [comment]
thanks for the detail @mmlb !
