### ISSUE TITLE
Add support for UEFI HTTP Boot

### ISSUE THREAD

**Issue by rgl** [tinkerbell/boots#210]
## Expected Behaviour

I expected to be able to use [UEFI HTTP Boot](https://github.com/tianocore/tianocore.github.io/wiki/HTTP-Boot) to boot a machine.

## Current Behaviour

Only PXE Boot is supported.

## Possible Solution

I've got dnsmasq serving HTTP Boot at:

https://github.com/rgl/talos-vagrant/blob/6ce54f83e4066bc60415d697f5c4a7a6cd5ac561/provision-dnsmasq.sh#L53-L59

**Comment by mmlb** [comment]
Am I right thinking that you want to keep boot's dhcp support and detect a UEFI machine and serve the http script instead of iPXE binary?

**Comment by mmlb** [comment]
Re opening because I had to revert #216 (due to #225). I've split the one commit from this PR to multiple independent ones to facilitate bisecting (currently at https://github.com/mmlb/boots/tree/split-and-fix-http-boot-for-c2.large.arm for now).
