### ISSUE TITLE
Move ipxe to a dedicated repository?

### ISSUE THREAD

**Issue by rgl** [tinkerbell/boots#213]
Currently ipxe is built in this repository, that makes the build of boots take longer and is more complex.

What do you think about:

1. moving the ipxe build to the boots-ipxe repository.
2. build ipxe in a GitHub Actions inside a docker container using buildx from a ubuntu 20.04 image.
3. publish an artifact for each arch as a GitHub Release.
4. modify the boots build to use the GitHub Release.

This would make things simpler from the boots build perspective and for someone that is trying to understand and build boots.

**Comment by mmlb** [comment]
Hey @rgl this sounds like a great suggestion, I like it. There really is no need to be wasting electricity building ipxe over and over again.

I have just 2 push backs.
1. I don't see the benefit of building using buildx over make
2. I'd rather stick with nix's pinned inputs over ubuntu.
