### ISSUE TITLE
allow adding options to DHCP Offer

### ISSUE THREAD

**Issue by Ottovsky** [tinkerbell/boots#23]
Currently it is assumed that server will figure out the tftp server from `Next Server` field in DHCP Offer, unfortunately it is not always a case, and for example Raspberry Pie 4, requires `option 66` to be explicitly set in DHCP offering, otherwise RPi4 is ignoring DHCP responses. It would be helpful to be able to set in hardware, target definition the values for hardware specific dhcp options.

**Comment by fonsecas72** [comment]
@Ottovsky did you managed to make boots/tinkerbell work with a raspberry pi 4 ?

**Comment by Ottovsky** [comment]
Hey @fonsecas72 , yes I made it work, here is a description how I did it https://github.com/ContainerSolutions/tinkerbell-rpi4-workflow.

**Comment by fonsecas72** [comment]
I'm trying to make it work for some days and still struggling to understand why it does not work. Did you followed exactly the setup from that repo? Any tweaks? 😔

**Comment by Ottovsky** [comment]
It worked for me, but it was a year ago, and I haven't checked the setup since then, so not sure if the current tinkerbell version will still work with rpi4 :(

**Comment by fonsecas72** [comment]
the kernel and root fs from that repo are not available anymore. perhaps that's what I'm missing 🤔 

mine just stops here 

![image](https://user-images.githubusercontent.com/1098293/120889243-0ca89900-c5f4-11eb-8de0-2f1f7f6d86d2.png)

**Comment by Ottovsky** [comment]
Yes, unfortunately I am no longer with Container Solutions, so can't check what is wrong with the links, I will check if I have any of those artifacts somewhere, so I can re-upload them, if not I posted some hints in this [issue](https://github.com/ContainerSolutions/tinkerbell-rpi4-workflow/issues/6) on how to build your own initramfs and kernel for rpi4

**Comment by fonsecas72** [comment]
thanks! that's useful 🙇

**Comment by nshalman** [comment]
Is it safe to close this issue as https://github.com/ContainerSolutions/tinkerbell-rpi4-workflow contains a successful implementation of provisioning, @Ottovsky?
@fonsecas72 were you able to get things working?

**Comment by Ottovsky** [comment]
If no one else is insisting on this feature, feel free to close
