### ISSUE TITLE
Doc: dead link in iPXE Doc on main branch

### ISSUE THREAD

**Issue by nicop311** [tinkerbell/boots#270]
Hello all :smiley: 
There is a dead link on **main** branch in the file [docs/IPXE.md](https://github.com/tinkerbell/boots/blob/c670ca8c03d5e7c4b951cac56724d21331fb7568/docs/IPXE.md):

At [this line](https://github.com/tinkerbell/boots/blob/c670ca8c03d5e7c4b951cac56724d21331fb7568/docs/IPXE.md?plain=1#L9), link `[ipxe/ipxe/](../ipxe/ipxe/)` is dead. And I don't know where the `.h` files are or if they exist on **main** branch.

However on branch/tag [v0.6.0](https://github.com/tinkerbell/boots/tree/v0.6.0), the folder `ipxe/ipxe/` exist with the `*.h` files.

**Comment by jacobweinstock** [comment]
Hey @nicop311, thanks for reporting this. We've actually moved ipxe building to another repo. https://github.com/tinkerbell/ipxedust We need to clean up this bad link. The doc lives here: https://github.com/tinkerbell/ipxedust/blob/main/docs/IPXE.md
