### ISSUE TITLE
boots should not panic on bad hardware data

### ISSUE THREAD

**Issue by Ottovsky** [tinkerbell/boots#28]
I made a mistake in my hardware data definition and I observed a fatal panic in the boots, which crashed it completely. I don't think it is a suitable behaviour, in my opinion it would be better to recover from panic and log error message, allowing boots to continue operating. 
The panic was caused by the code in https://github.com/tinkerbell/boots/blob/master/job/job.go#L79 .

**Comment by nathangoulding** [comment]
This would be good to address, i.e. returning an error instead of panicing.

**Comment by Ottovsky** [comment]
Looks good now, closing the issue.
