### ISSUE TITLE
Customscript error handling does not seem correct

### ISSUE THREAD

**Issue by rgl** [tinkerbell/boots#329]
The code at https://github.com/tinkerbell/boots/blob/384b68b37cdf2861158ed756ab102ab13ab1971d/ipxe/auto.go#L85-L89 does not seem correct.

When, for some reason, there is a problem interpreting what we put in the Hardware object (e.g. an invalid url), the error is never sent/displayed anywhere, and it will make things really hard to troubleshoot.

And, IMHO, the worse part, it will just boot the default iPXE script, which is not what I intent to do.

This should be changed to not ignore any errors (and not having a custom script in the Hardware object should not be considered an error too). When there is an error, it should log the error and abort the boot.

Also, returning a 404 when there is error at https://github.com/tinkerbell/boots/blob/384b68b37cdf2861158ed756ab102ab13ab1971d/ipxe/auto.go#L91-L92 does not seem correct too and should be changed to a 500.

What do you think?

**Comment by jacobweinstock** [comment]
Hey @rgl, thanks for the report. Yeah, that all sounds very reasonable. Would you like to work on this? Totally fine if not. I will  take it on, no problem. I'm fine either way, let me know. thanks again for the report!

**Comment by jacobweinstock** [comment]
Hey @rgl , i put a PR together for this. Still want to add a few more tests. Please check it out and let me know what you think. Thanks!

https://github.com/tinkerbell/boots/pull/330

**Comment by rgl** [comment]
@jacobweinstock, its looking good.

But now that I've read a bit more about the code, I think, I will be stuck. As there is no way for a custom script/custom url to have the data about the Hardware and Tinkerbell in the Go template. So the custom boot script will not known how to reach Tinkerbell/Hegel to have the Hardware details.

I have to say that I'm trying to replace Hook OSIE with [Debian OSIE](https://github.com/rgl/tinkerbell-debian-osie). But for that, in the custom script, I think I need to be able to have access to the same data as hook in https://github.com/tinkerbell/boots/blob/384b68b37cdf2861158ed756ab102ab13ab1971d/ipxe/auto.go#L118-L156

**Comment by rgl** [comment]
I'm also trying to play with [ORAS](https://github.com/oras-project/oras) using the [zot registry](https://github.com/project-zot/zot), which means the files will be served from an OCI registry, which means the urls will be somewhat odd like this:

```
kernel: http://registry.example.test:5001/v2/tinkerbell-debian-osie/osie/blobs/sha256:0f6e36da407dcb3124b09cc78ff0522a809ee6f1e3d9b55b1d2e683b4d88b2ec
initrd: http://registry.example.test:5001/v2/tinkerbell-debian-osie/osie/blobs/sha256:970f189d1606f63999c7a5bac31d81e13dd01fa7c23a11387fba6d401e404520
```

Unless I find a way to make them "pretty", that is, have the expected boots filenames (e.g. `vmlinuz-x86_64`), using the boots `-osie-url` does not seem it would work.

**Comment by jacobweinstock** [comment]
ah ok, i see. thanks for sharing this. I think it's reasonable to make the data available to the custom ipxe script. After #330 lands, i will work on making the data available.

**Comment by rgl** [comment]
That would be greatly appreciated!

Maybe, we could also have a way to set a custom ipxe script globally? Like the per hardware one and in a similar way as the =osi=url cli argument.
