### ISSUE TITLE
Produce a binary release, for multiple architectures

### ISSUE THREAD

**Issue by vielmetti** [tinkerbell/boots#4]
To aid in bootstrapping and testing, the project should publish a binary release (for at least two architectures) to allow users to get their hands on this code without needing at the very outset to have a full development environment.

**Comment by vielmetti** [comment]
Blocked on #5.

**Comment by invidian** [comment]
https://goreleaser.com/ is handy for generating binaries for multiple architectures/platforms. Also supports nice GitHub integration.

**Comment by displague** [comment]
I have a branch that can be used to build multi-arch builds, I don't know how this affects the normal drone build environment. I'd be happy to make a PR of this for further discussion:
https://github.com/tinkerbell/boots/compare/master...displague:multiarch?expand=1#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by displague** [comment]
Fixed by #94 and #107
