### ISSUE TITLE
dhcp lease time issues

### ISSUE THREAD

**Issue by nathangoulding** [tinkerbell/boots#45]
With the introduction of new data model, it does not use the environment variable for default DHCP lease time. In addition, there is not a default lease time. This causes the value of 0 to be used, which creates a flood of DHCP requests to the DHCP server because of the short lease time. We should default this to 86400 if the user does not supply one.

**Comment by rgl** [comment]
Its strange, but even setting the lease time in the hardware (nor dns servers) as the following, it does not work (boots still sends dhcp ack with 0 lease time and with 8.8.8.8 dns servers). Was this supposed to work with current boots?

```json
# docker exec -i deploy_tink-cli_1 tink hardware id 00000000-0000-4000-8000-c03fd56cb75a | jq .
{
  "metadata": {
    "state": "provisioning",
    "instance": {},
    "facility": {
      "facility_code": "onprem"
    }
  },
  "network": {
    "interfaces": [
      {
        "dhcp": {
          "mac": "c0:3f:d5:6c:b7:5a",
          "hostname": "nuc",
          "lease_time": 86400,
          "name_servers": [
            "1.1.1.1",
            "1.0.0.1"
          ],
          "arch": "x86_64",
          "uefi": true,
          "iface_name": "eth0",
          "ip": {
            "address": "10.10.10.13",
            "netmask": "255.255.255.0",
            "gateway": "10.10.10.2"
          }
        },
        "netboot": {
          "allow_pxe": true,
          "allow_workflow": true
        }
      }
    ]
  },
  "id": "00000000-0000-4000-8000-c03fd56cb75a"
}

```
