### ISSUE TITLE
Make TFTP session timeout tunable (defaults to 3 seconds)

### ISSUE THREAD

**Issue by lukaskalvenas** [tinkerbell/boots#66]
It would be nice to have the possibility to edit the TFTP session timeout for each worker server. Currently, if the worker server does not respond within 3-6 seconds, TFTP times out and the operating system installation ultimately fails. 

## Current Behaviour
CLIENT MAC ADDR: $MAC  GUID: 00000000 0000 0000 0000 AC1F6BA50120
CLIENT IP: xxx.xxx.xxx.xxx  MASK: yyy.yyy.yyy.yyy  DHCP IP: zzz.zzz.zzz.zzz
GATEWAY IP: aaa.aaa.aaa.aaa
PXE-E32: TFTP open timeout
PXE-M0F: Exiting Intel Boot Agent.

## Steps to Reproduce (for bugs)

In our case, because of the network infrastructure, the server is a bit slower to respond in that part of the world. 

## Context

Because the server takes longer to respond, TFTP's TTL expires and the session times out, ultimately failing the whole deployment process.

## Your Environment

Provisioner running CentOS 7, deploying to another bare-metal server.

**Comment by gianarb** [comment]
Just sharing what I discovered. We use a lib called [betawaffle/tftp-go](https://github.com/betawaffle/tftp-go). It serves a UDP server with a handler that implements TFTP. From my understanding, the timeout can't be changed:

https://github.com/betawaffle/tftp-go/blob/master/server.go#L164

serve() does not accept a timeout and its value is set by default to `3s`. @mmlb can you confirm or deny? I feel a bit lost :)

**Comment by mmlb** [comment]
all true. I've been wanting to either fork that repo and make some changes for a while now or look into an alternative. This may be the time to do so... probably the fork ;).

**Comment by gianarb** [comment]
@mmlb apparently we have a fork now 

https://github.com/tinkerbell/tftp-go

I think @mikemrm did that, can we update that fork and fix this issue?

**Comment by jacobweinstock** [comment]
iPXE binaries served via tftp now have a configurable timeout. please see: https://github.com/tinkerbell/boots/blob/5faab799ed5c1ceea501df7b3768effbbd7261ed/cmd/boots/main.go#L401
