### ISSUE TITLE
Make use of params command optional for phone-home

### ISSUE THREAD

**Issue by geekgonecrazy** [tinkerbell/boots#78]
Working through getting my physical servers working with tinkerbell to start doing some experimentation.. they fail saying the “params” command is not found.

Leased from datacenter so flashing or updating ipxe might not be possible or ideal.

## Expected Behaviour

Boots

## Current Behaviour

Errors out at params not found

## Possible Solution

Maybe hardware option?  Or use query string

## Steps to Reproduce (for bugs)

1. Run ipxe with out params built in
2. Try to boot

## Context

My solution was just to remove the params here:
https://github.com/tinkerbell/boots/blob/master/ipxe/script.go#L34

Then just let it phone home even with out params.  Seems like using ?body=${body}&type=${body} might could work.  I’m also not even sure if needed? Looking at the phone home code seems like it’s mostly ignored?

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details: tinkerbell it’s self kvm on the network

* Link to your project or a code example to reproduce issue:

**Comment by gianarb** [comment]
I encountered the same issue when trying to use `osie` locally. The problem here is that `osie` `init.sh` fails if phone-home does not get resolved. This should not happen but it happens now because `osie` still uses a lot of things that only Packet needs. 

@geekgonecrazy I know from Slack that you are doing something a bit different here because your cloud provider (ovh) does not give you full control. But technically the phone-home is a feature that Tinkerbell provides.

**Comment by geekgonecrazy** [comment]
I can see some potential use cases for the phone home in general.  

I tried using "params" even from the shell and the command is for sure not present in the version compiled and on this server. According to this: https://ipxe.org/cmd/params the ipxe had to be compiled with PARAM_CMD option defined.

I had some issues with tftp as well I think that you might be referring to.  No clue if related to this or not.  

But in this case it loaded the ipxe script fine but then errored out when trying to run params command.  Soon as I took that section out and changed the code to:

```
imgfetch ${tinkerbell}/phone-home
imgfree
```
It worked fine

**Comment by gianarb** [comment]
I think you can avoid `params` if your provider does not support that, you can replace manually the concrete values where you see `${}`. 

Anyway, I think in 2 months we will have a very different `osie` image, smaller and easier to customize.

**Comment by geekgonecrazy** [comment]
I think maybe misunderstood my problem.

All of the other ${} substitutions and variables work just like intended.  By params command I mean the literal [ipxe params command](https://ipxe.org/cmd/params) used here on this line: https://github.com/tinkerbell/boots/blob/master/ipxe/script.go#L34

All other ${} substitutions and variables work fine.  It’s simply that block:

https://github.com/tinkerbell/boots/blob/master/ipxe/script.go#L34-L36

**Comment by geekgonecrazy** [comment]
This better explains the full thing setup and patch: https://geekgonecrazy.com/2020/09/07/tinkerbell-or-ipxe-boot-on-ovh/

**Comment by mmlb** [comment]
Hey @geekgonecrazy in Packet we *always* boot our own version of ipxe exactly to avoid this situation (iPXE built without some things we need). I think removing the params would be fine in general, but is just a symptom of a bigger issue. Can you chain your own ipxe binary? That would be the most compatible and future-proof solution.

**Comment by mmlb** [comment]
@geekgonecrazy you can do this like `chain tftp://${tinkerbell}/one_of_the_ipxe_files`, where one_of_the_ipxe_files is one of the files https://github.com/tinkerbell/boots/blob/master/job/dhcp.go#L105-L113

**Comment by geekgonecrazy** [comment]
@mmlb ah interesting idea.. 

Downside is.. would have to some how make it only check net1 and not net0.  At least in my case.  Since their server always replies on net0 with my script (or theirs if I don't have one set in their api).

So would have to some how make the chained ipxe version only check net1.. or.. the script some how be able to detect its in my version of ipxe and chain to boots instead of ipxe.

Something like:
```
if version_with_params
chain http://${tinkerbell}/auto.ipxe
else
chain tftp://${tinkerbell}/ipxe-version
fi
```

**Comment by geekgonecrazy** [comment]
```
#!ipxe
ifclose net0 
dhcp net1 
set iface net1 

params || goto load_ipxe
chain --autofree http://10.10.5.1/auto.ipxe || exit

:load_ipxe
chain tftp://10.10.5.1/ipxe.efi || shell
```

actually I think this will work.. if only I can ever get ipxe.efi to boot.  It just hangs there indefinitely

**Comment by mmlb** [comment]
@geekgonecrazy glad that works. We do have a patched version number which you can use to branch off of too. Its used to detect iPXEs burned into nics and our own iPXE. Its used in boot's dhcp handling code, but I'm not sure if ipxe sends the version info when fetching ipxe script though.

**Comment by geekgonecrazy** [comment]
well it works as far as the logic works.  But the actual booting from the ipxe versions shipped does not.  I left for many hours and it just hangs there. 

So we might need to fork off into another issue for this specifically.  But, none of the ipxe methods work from here. Not sure if any way to debug, but stays on:

![image](https://user-images.githubusercontent.com/51996/92660158-7f802000-f2bf-11ea-92fa-cbfb30e1331f.png)

**Comment by geekgonecrazy** [comment]
Tried out the various ones from https://boot.ipxe.org 

https://boot.ipxe.org/snponly.efi - this one finally worked.  So would need to add that one, and determine what criteria is used to offer that one up to boot

**Comment by mmlb** [comment]
I think its time to fork off into a different issue. snponly looks like something we'd want all the time anyway to be honest.

**Comment by mmlb** [comment]
Also looking at the foreman config those would map to https://github.com/tinkerbell/boots/blob/master/dhcp/pxe.go#L23-L26 iirc.

**Comment by mmlb** [comment]
DDG points me https://github.com/jljusten/tianocore/wiki/EBC-FAQ and similar, so it must be true.

**Comment by geekgonecrazy** [comment]
According to: https://tools.ietf.org/html/rfc4578#section-2.1 architecture type 7 is:  EFI BC

**Comment by jacobweinstock** [comment]
I believe with `snp.efi` this issue is resolved? @geekgonecrazy, please reopen if this is not the case.
